### PR TITLE
Add library template and corresponding css

### PR DESCRIPTION
**Pull request by oagutu**
[page url] https://oagutu.github.io/Designs/UI/library.html

library_screenshot

### CODE REVIEW

**Comment by Xerrex** [comment]
The styling is on point.

**Comment by 3V0L** [comment]
The look is very nice and professional. A personal suggestion would be to limit the height of the images so that they can have a uniform look.

**Comment by kenyanerd** [comment]
HI ogutu good styling bro

**Comment by Nerldy** [comment]
Was it intentional to have the pics different sizes? Not that there is anything wrong. I like.

**Comment by kiamakelvinsmalls** [comment]
dope staff

**Comment by oagutu** [comment]
@3V0L , @Nerldy  The different sized pics were intentional. I was going for a 'pinterest-y' look.

**Comment by faustineomuya** [comment]
Really Creative

**Pull request merged**
